Translate docs/tasks/tools/install-kubectl.md
k8smeetup/kubernetes.github.io pull request #151
Opened 2017-09-15 06:08 UTC by xingzhou

2017-09-16 13:12 UTC, jimexist requested changes

2017-09-16 13:12 UTC, Jimexist commented on docs/tasks/tools/install-kubectl.md
> +标题：安装和设置kubectl
`title` 不翻译

2017-09-16 13:13 UTC, Jimexist commented on docs/tasks/tools/install-kubectl.md
> +1. 通过以下命令下载kubectl的最新释出版：
`释出版` => 版本就行了

2017-09-16 13:14 UTC, Jimexist commented on docs/tasks/tools/install-kubectl.md
> +[了解如何启动并对外公开您的应用程序。](/docs/user-guide/quick-start)
暴露

2017-09-16 13:14 UTC, Jimexist commented
建议中英文中间加空格

2017-09-19 13:38 UTC, markthink commented
@xingzhou 刑老师更新一下吧

2017-10-16 03:04 UTC, xingzhou commented
Sorry for the late response, please take review, thanks!

2017-10-22 09:49 UTC, merged