tools-kompose-index-pr-2017-09-17
k8smeetup/kubernetes.github.io pull request #157
Opened 2017-09-17 15:52 UTC by GavinBF

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

![Allow edits from maintainers checkbox](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

2017-09-19 09:58 UTC, zhangqx2010 commented on docs/tools/kompose/index.md
> +标题: Kompose 概览
title不用翻译

2017-09-19 10:00 UTC, zhangqx2010 commented on docs/tools/kompose/index.md
> +`kompose` 是一个将`docker-compose`迁移到**kubernetes**的工具，`kompose`会把Docker Compose文件翻译成Kubernetes资源文件。
`docker-compose` 和 **kubernetes** ，后面的英文也是两边加空格

2017-09-19 10:05 UTC, zhangqx2010 commented on docs/tools/kompose/index.md
> +`kompose` 是从本地Docker管理到使用Kubernetes管理你的应用程序的便利工具。 Docker的转换撰写格式到Kubernetes资源清单可能不是精确的，但是当首次在Kubernetes上部署应用程序时，它会起到一定作用。
句号后面不用空格 local Docker development
后面一句读起来不通顺

2017-09-19 10:06 UTC, zhangqx2010 commented on docs/tools/kompose/index.md
> +如果你有一个Docker Compose的`docker-compose.yml`文件或者一个`docker-compose-bundle.dab`文件，可以通过kompose命令将它们生成为Kubernetes的deplyment、service的资源文件，如下所示：
Docker Distributed Application Bundle 未翻译

2017-09-19 10:13 UTC, zhangqx2010 requested changes
多处需要修改

2017-09-19 13:39 UTC, markthink commented
@GavinBF 更新一下吧

2017-09-26 07:36 UTC, GavinBF commented
@zhangqx2010 感谢老司机帮助

2017-09-27 03:26 UTC, merged