translate pull-image-from-private-registry-2017-9-15.md
k8smeetup/kubernetes.github.io pull request #162
Opened 2017-09-19 06:25 UTC by NickSu86

> NOTE: Please check the “Allow edits from maintainers” box (see image below) to  
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.

![Allow edits from maintainers checkbox](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

@markthink Please help review and merge , thank you

2017-09-19 10:15 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +这篇教程指导如何创建Pod并使用Secret从私有Docker仓库或者镜像源拉取镜像。
英文两边需要加空格

2017-09-20 02:47 UTC, zhangqx2010 requested changes
未全部review完成，建议译者自己review一遍后提交，翻译是请尽量遵循原文意思，遇到实在难表达的英文才使用意译。

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +然后输入你Docker的用户名和密码。
然后 --> 当提示时

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +登录过程会创建或者更新`config.json`文件，在这里会保存验证的口令。
`config.json` 两边加空格

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +**注意:** 如果你使用了Docker保存验证信息, 你不会看到`auth`而是`credsStore`和一样的值。
和一样的值？

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +## 理解你的 Secret
理解 Secret 
your可以不翻

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +想要知道你刚刚创建的 Secret 是什么，可以先看看 YAML 格式的 Secret：
知道 --> 理解

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +把这一串base64加密的数据复制赋值给`secret64`.
写入名为 `secret64` 的文件

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +**注意**: 确保`secret64`的值没有分割是完整的一行.
**重要**

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +**注意**: 确保`secret64`的值没有分割是完整的一行.
这里的line break应该指的是换行符

2017-09-20 02:47 UTC, zhangqx2010 commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
> +**注意**: 确保`secret64`的值没有分割是完整的一行.
`secret64` 文件

2017-09-22 07:35 UTC, NickSu86 commented
你好，我修改了一下，请再review一遍，谢谢

2017-09-22 09:57 UTC, markthink commented on docs/tasks/configure-pod-container/pull-image-private-registry.md
首行不能有空格，否则编译会有问题。

2017-09-26 03:28 UTC, NickSu86 commented
@markthink please help review and merge , thank you

2017-09-26 06:17 UTC, merged