admin-kubefed-init-pr-2017-10-15
k8smeetup/kubernetes.github.io pull request #256
Opened 2017-12-01 01:24 UTC by xiaosuiba

@markthink @zhangqx2010 please review at your convenience, thanks.

2017-12-01 14:16 UTC, zhangqx2010 reviewed
整体ok，几个小地方

2017-12-01 14:16 UTC, zhangqx2010 commented on docs/admin/kubefed_init.md
> +# 在本地 kubeconfig context 名为 bar 的主集群中使用 federation 名称 foo 初始化控制平面。
在本地 kubeconfig context 名为 bar 的主集群中使用名称 foo 初始化 federation 控制平面。

2017-12-01 14:16 UTC, zhangqx2010 commented on docs/admin/kubefed_init.md
> +      --cloud-provider-gce-lb-src-cidrs cidrs   在 GCE 防火墙中打开，用于负载均衡流量代理和健康检查的 CIDR（默认为 209.85.152.0/22,209.85.204.0/22,130.211.0.0/22,35.191.0.0/16）
在 GCE 防火墙中开放

2017-12-01 14:16 UTC, zhangqx2010 commented on docs/admin/kubefed_init.md
> +      --insecure-skip-tls-verify                如果为 true，则不会对 server 的证书进行有效性验证。这将导致不安全的 HTTPS 连接。
这将导致 HTTPS 连接变得不安全。

2017-12-01 14:16 UTC, zhangqx2010 commented on docs/admin/kubefed_init.md
> +      --stderrthreshold severity                高于或等于此级别门限的日志将输出到 stderr （默认为 2）。
高于或等于此级别阈值的日志

2017-12-02 02:11 UTC, xiaosuiba commented on docs/admin/kubefed_init.md
> +# 在本地 kubeconfig context 名为 bar 的主集群中使用 federation 名称 foo 初始化控制平面。
这个我分成两句吧
在主集群中为名为 foo 的 federation 初始化控制平面，其本地 kubeconfig context 为 bar

2017-12-02 02:14 UTC, xiaosuiba commented
@zhangqx2010  thanks for reviewing
cc @markthink, please check and merge.

2017-12-02 09:12 UTC, zhangqx2010 requested changes
有个空格要删一下

2017-12-02 09:12 UTC, zhangqx2010 commented on docs/admin/kubefed_init.md
> +  * [kubefed](kubefed.md) - 使用 kubefed 控制 Kubernetes Cluster Federation
这里好像多了个空格

2017-12-03 12:33 UTC, xiaosuiba commented
cc @markthink

2017-12-03 14:40 UTC, merged